export const PARTICIPANT_REGISTRATION_REQUEST = 'PARTICIPANT_REGISTRATION_REQUEST';
export const PARTICIPANT_REGISTRATION_RESPONSE = 'PARTICIPANT_REGISTRATION_RESPONSE';
export const PARTICIPANT_REGISTRATION_DEFAULT_STATE =
  'PARTICIPANT_REGISTRATION_DEFAULT_STATE';
